      SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD,
     1 RPL,DDSDDT,DRPLDE,DRPLDT,
     2 STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME,
     3 NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT,
     4 CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)
C
      CHARACTER*80 CMNAME
      DOUBLE PRECISION STRESS(NTENS),STATEV(NSTATV),
     1 DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS),
     2 STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1),
     3 PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3),
     4 JSTEP(4)
C     ELASTIC USER SUBROUTINE
      PARAMETER (ONE=1.0D0, TWO=2.0D0)
      E=PROPS(1)
      ANU=PROPS(2)
      ALAMBDA=E/(ONE+ANU)/(ONE-TWO*ANU)
      BLAMBDA=(ONE-ANU)
      CLAMBDA=0.5*(ONE-TWO*ANU)
      C1 = ALAMBDA*BLAMBDA
      C2 = ALAMBDA*CLAMBDA
      C3 = ALAMBDA*ANU
      DO I=1,NTENS
         DO J=1,NTENS
            DDSDDE(I,J)=0.0D0
         ENDDO
      ENDDO
      DDSDDE(1,1)=C1
      DDSDDE(2,2)=C1
      DDSDDE(3,3)=C1
      DDSDDE(4,4)=C2
      DDSDDE(5,5)=C2
      DDSDDE(6,6)=C2
      DDSDDE(1,2)=C3
      DDSDDE(1,3)=C3
      DDSDDE(2,3)=C3
      DDSDDE(2,1)=C3
      DDSDDE(3,1)=C3
      DDSDDE(3,2)=C3

c     STRESS = STRESS + MATMUL(DDSDDE, DSTRAN)
      STRESS = MATMUL(DDSDDE, STRAN + DSTRAN)
      RETURN
      END
