version: 2


# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "mambaforge-latest"

conda:
  environment: environment_docs.yml

mkdocs:
  configuration: mkdocs.yml

