language: python
python:
    - "3.7"

script:
    - sudo apt update && sudo apt install -y pandoc
    - doit

deploy:
    privder: pages
    skip_cleanup: true
    local_dir: "website"
    on:
        branch: master
