language: python
python:
    - "3.7"

script:
    - sudo apt update && sudo apt install -y pandoc
    - doit

#jobs:
#    include:
#        - stage: website
#          script:
#              - travis_retry timeout 120 docker pull fb77/sphinx
#              - docker run -itd --name sphinx -v $(pwd):/repo fb77/sphinx
#              - docker exec sphinx bash -c "pip install doit"
#              - docker exec sphinx bash -c "cd repo && doit"
#
#          deploy:
#              privder: pages
#              skip_cleanup: true
#              github_token: $TRAVIS_GH_PAGES_KEY
#              local_dir: "website"
#              on:
#                  branch: master
