name: fenics-constitutive-docs
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - mkdocs
  - mkdocs-bibtex
  - python-markdown-math
  - mkdocs-jupyter
  - pymdown-extensions
  - mkdocstrings-python
  - mkdocs-gen-files
  #- sympy
  #- pyvista
  #- tqdm
  - pip
  #- meshio
  - fenics-dolfinx=0.6.0
  #- libadios2=2.10.1
  - matplotlib
  - pint
  - pip:
    - mkdocs-include-dir-to-nav
    - -e .


