name: fenics-constitutive
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - fenics-dolfinx>=0.9.0
  - adios4dolfinx
  - numpy
  - pip
  - pytest
  - pytest-mpi
  - maturin
  - pip:
    - -e .