{% set name = "constitutive" %}
{% set version = "0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/BAMresearch/fenics-constitutive
  git_tag: conda-recipe

build:
  number: 0
  skip: true  # [py2k]
  skip: true  # [py<37]
  skip: true  # [win or osx]
  script: 
    - {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv

requirements:
  build:
    - {{ compiler('c') }}

  host:
    - pip
    - python
    - setuptools
    - cmake >=3.21
    - eigen
    - pybind11

  run:
    - python
    - numpy
    - fenics >=2019.1.0
    - mshr >=2019.1.0
    - matplotlib  
    - fenics_helpers

test:
  imports:
    - constitutive
    - dolfin
  source_files:
    - test
  commands:
    - python -m unittest discover -v -s test

about:
  home: https://github.com/BAMresearch/fenics-constitutive
  summary: Complex constitutive models beyond the FEniCS UFL.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - pdiercks
