name: Conda package

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: build-and-publish
        uses: MichaelsJP/conda-package-publish-action@v1.0.0
        with:
          subDir: ".conda"
          AnacondaToken: ${{ secrets.ANACONDA_TOKEN }}
          platforms: "linux-aarch64"
          override: true  # override uploaded package
          dry_run: false  # If true, only build without publishing
