name: Conda package

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          # add channel pdiercks for `fenics_helpers`
          channels: conda-forge,pdiercks,defaults
          channel-priority: true

      - name: Build conda package
        # properly activate shell
        shell: bash -l {0}
        env:
          ANACONDA_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
        run: |
          conda install conda-build anaconda-client conda-verify
          conda config --set anaconda_upload yes
          cd $GITHUB_WORKSPACE
          conda build --token "$ANACONDA_TOKEN" .conda -m .conda/conda_build_config.yaml
