name: tests
on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow once per day at 3:15am
  schedule:
    - cron: '3 16 * * *'

env:
  CACHE_NUMBER: 1 # increase to reset cache manually

jobs:
  tests:
    runs-on: ubuntu-latest


    steps:
      - name: checkout repo content
        uses: actions/checkout@v2

      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
            miniforge-version: latest
            activate-environment: fenics-constitutive
            use-mamba: true

      - name: Set cache date
        run: echo "DATE=$(date +'%Y%m%d')" >> $GITHUB_ENV

      - name: Update environment
        run: mamba env update -n fenics-constitutive -f environment.yml

      - name: pytest
        id : pytest
        shell: bash -l {0}
        run: |
          pytest --with-mpi
      - name: pytest with MPI
        id: pytest_mpi
        shell: bash -l {0}
        run: |
          mpirun -np 2 pytest -s tests/test_maps.py --with-mpi




